spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://localhost:3306/jeesite?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&&allowMultiQueries=true&autoReconnect=true
  username: root
  password:
  driverClassName: com.mysql.jdbc.Driver
#dataSource Pool configuration
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  exceptionSorter: true
  testOnReturn: false
  poolPreparedStatements: true
  #filters: stat,wall,log4j
  filters: stat
  maxPoolPreparedStatementPerConnectionSize: 20
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  useGlobalDataSourceStat: true


mybatis:
 config-location: classpath:mybatis-config.xml
 mapper-locations: classpath:/mapper/**/*.xml
 type-aliases-package: com.jpm.*